"""
outbound_audit.py — Parse and analyze outbound connection logs from firewalld.

Designed for Rocky Linux hoppers running Ollama. Parses the logs generated by
setup_outbound_logging.sh and surfaces the interesting stuff:

  1. Summary report:  Top destinations, ports, source processes, hourly patterns
  2. Anomaly detection: Flags first-seen destinations, unusual ports, Ollama activity

Usage:
    # Analyze today's logs (default)
    sudo python outbound_audit.py

    # Analyze a specific log file
    sudo python outbound_audit.py -f /var/log/outbound-connections.log

    # Only show Ollama's outbound activity
    sudo python outbound_audit.py --ollama-only

    # Analyze last 24 hours and flag anything new vs. a known-good baseline
    sudo python outbound_audit.py --baseline /etc/outbound-baseline.json

    # Generate a baseline from current logs (run this once things look "normal")
    sudo python outbound_audit.py --save-baseline /etc/outbound-baseline.json

    # Filter to a time window
    sudo python outbound_audit.py --after "2025-03-20 08:00" --before "2025-03-20 17:00"

    # Show top 20 instead of default top 10
    sudo python outbound_audit.py -n 20
"""

import argparse
import json
import os
import re
import socket
import sys
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path

# =============================================================================
# Color helpers — no dependencies needed
# =============================================================================

class C:
    """ANSI color codes. Disabled if not a TTY."""
    _enabled = sys.stdout.isatty()

    RESET   = "\033[0m"   if _enabled else ""
    BOLD    = "\033[1m"    if _enabled else ""
    DIM     = "\033[2m"    if _enabled else ""
    RED     = "\033[91m"   if _enabled else ""
    GREEN   = "\033[92m"   if _enabled else ""
    YELLOW  = "\033[93m"   if _enabled else ""
    BLUE    = "\033[94m"   if _enabled else ""
    MAGENTA = "\033[95m"   if _enabled else ""
    CYAN    = "\033[96m"   if _enabled else ""
    WHITE   = "\033[97m"   if _enabled else ""
    BG_RED  = "\033[41m"   if _enabled else ""


# =============================================================================
# Log parsing
# =============================================================================

# Matches kernel log lines from iptables/firewalld LOG target
# Example: Mar 20 14:23:01 hopper1 kernel: OUTBOUND_CONN_TCP: IN= OUT=eth0 SRC=10.0.0.5 DST=104.18.32.7 ...
LOG_PATTERN = re.compile(
    r"^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+"  # syslog timestamp
    r"(?P<hostname>\S+)\s+"                           # hostname
    r"kernel:\s*"                                      # kernel prefix
    r"(?P<prefix>\S+?):\s+"                            # our log prefix (OUTBOUND_CONN_TCP, OLLAMA_OUTBOUND_TCP, etc.)
    r"(?P<fields>.*)"                                  # key=value fields
)

FIELD_PATTERN = re.compile(r"(\w+)=(\S*)")

# Well-known ports for display
KNOWN_PORTS = {
    22: "SSH", 25: "SMTP", 53: "DNS", 80: "HTTP", 123: "NTP",
    443: "HTTPS", 465: "SMTPS", 587: "SMTP-SUB", 853: "DNS-TLS",
    993: "IMAPS", 995: "POP3S", 3306: "MySQL", 5432: "PostgreSQL",
    5672: "AMQP", 6379: "Redis", 8080: "HTTP-ALT", 8443: "HTTPS-ALT",
    9090: "Prometheus", 9200: "Elasticsearch", 11434: "Ollama",
    27017: "MongoDB",
}

# Ports that are generally expected for outbound traffic
NORMAL_OUTBOUND_PORTS = {53, 80, 123, 443, 853}


def parse_syslog_timestamp(ts_str: str, year: int = None) -> datetime:
    """Parse syslog-style 'Mar 20 14:23:01' timestamps."""
    if year is None:
        year = datetime.now().year
    try:
        return datetime.strptime(f"{year} {ts_str}", "%Y %b %d %H:%M:%S")
    except ValueError:
        return None


def parse_log_line(line: str):
    """Parse a single log line into a structured dict."""
    m = LOG_PATTERN.match(line.strip())
    if not m:
        return None

    fields_raw = m.group("fields")
    fields = dict(FIELD_PATTERN.findall(fields_raw))

    entry = {
        "timestamp": parse_syslog_timestamp(m.group("timestamp")),
        "hostname": m.group("hostname"),
        "prefix": m.group("prefix"),
        "src": fields.get("SRC", ""),
        "dst": fields.get("DST", ""),
        "dpt": int(fields.get("DPT", 0)),
        "spt": int(fields.get("SPT", 0)),
        "proto": fields.get("PROTO", "").upper(),
        "out_iface": fields.get("OUT", ""),
        "in_iface": fields.get("IN", ""),
        "uid": fields.get("UID", ""),
        "is_ollama": "OLLAMA" in m.group("prefix"),
        "is_blocked": "BLOCKED" in m.group("prefix"),
        "raw": line.strip(),
    }
    return entry


def read_log_file(path: str):
    """Read and parse an entire log file."""
    entries = []
    try:
        with open(path, "r") as f:
            for line in f:
                entry = parse_log_line(line)
                if entry and entry["timestamp"]:
                    entries.append(entry)
    except FileNotFoundError:
        print(f"{C.RED}ERROR:{C.RESET} Log file not found: {path}")
        print(f"  Has setup_outbound_logging.sh been run yet?")
        sys.exit(1)
    except PermissionError:
        print(f"{C.RED}ERROR:{C.RESET} Permission denied: {path}")
        print(f"  Try running with sudo.")
        sys.exit(1)
    return entries


# =============================================================================
# DNS resolution (cached)
# =============================================================================

@lru_cache(maxsize=4096)
def resolve_ip(ip: str) -> str:
    """Reverse-DNS lookup with caching. Returns hostname or original IP."""
    try:
        hostname, _, _ = socket.gethostbyaddr(ip)
        return hostname
    except (socket.herror, socket.gaierror, OSError):
        return ip


def fmt_dst(ip: str, resolve: bool = True) -> str:
    """Format a destination: 'hostname (IP)' or just 'IP'."""
    if not resolve:
        return ip
    hostname = resolve_ip(ip)
    if hostname != ip:
        return f"{hostname} ({ip})"
    return ip


# =============================================================================
# Reporting
# =============================================================================

def print_header(title: str):
    width = 78
    print()
    print(f"{C.BOLD}{C.CYAN}{'═' * width}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}  {title}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}{'═' * width}{C.RESET}")


def print_section(title: str):
    print(f"\n{C.BOLD}{C.YELLOW}── {title} {'─' * (74 - len(title))}{C.RESET}")


def print_table(headers, rows, col_widths=None):
    """Print a simple aligned table."""
    if not rows:
        print(f"  {C.DIM}(none){C.RESET}")
        return

    if col_widths is None:
        col_widths = []
        for i, h in enumerate(headers):
            max_w = len(h)
            for row in rows:
                if i < len(row):
                    # Strip ANSI for width calculation
                    clean = re.sub(r"\033\[[0-9;]*m", "", str(row[i]))
                    max_w = max(max_w, len(clean))
            col_widths.append(min(max_w, 60))

    # Header
    header_line = "  "
    for i, h in enumerate(headers):
        header_line += f"{C.BOLD}{h:<{col_widths[i]}}{C.RESET}  "
    print(header_line)
    print(f"  {C.DIM}{'─' * (sum(col_widths) + 2 * len(col_widths))}{C.RESET}")

    # Rows
    for row in rows:
        line = "  "
        for i, cell in enumerate(row):
            clean = re.sub(r"\033\[[0-9;]*m", "", str(cell))
            padding = col_widths[i] - len(clean)
            line += f"{cell}{' ' * max(0, padding)}  "
        print(line)


def port_label(port: int) -> str:
    """Return 'port/SERVICE' or just 'port'."""
    name = KNOWN_PORTS.get(port, "")
    if name:
        return f"{port}/{name}"
    return str(port)


def print_summary_report(entries, top_n, resolve):
    """Print the summary report with top destinations, ports, etc."""
    print_header("OUTBOUND CONNECTION SUMMARY REPORT")

    total = len(entries)
    if total == 0:
        print(f"\n  {C.DIM}No log entries found in the specified range.{C.RESET}")
        return

    ollama_entries = [e for e in entries if e["is_ollama"]]
    blocked_entries = [e for e in entries if e["is_blocked"]]
    allowed_entries = [e for e in entries if not e["is_blocked"]]

    ts_min = min(e["timestamp"] for e in entries)
    ts_max = max(e["timestamp"] for e in entries)

    print(f"\n  {C.BOLD}Time range:{C.RESET}  {ts_min.strftime('%Y-%m-%d %H:%M')} → {ts_max.strftime('%Y-%m-%d %H:%M')}")
    print(f"  {C.BOLD}Total connections:{C.RESET}  {total:,}")
    print(f"  {C.BOLD}Allowed:{C.RESET}  {C.GREEN}{len(allowed_entries):,}{C.RESET}    "
          f"{C.BOLD}Blocked:{C.RESET}  {C.RED}{len(blocked_entries):,}{C.RESET}    "
          f"{C.BOLD}Ollama-originated:{C.RESET}  {C.MAGENTA}{len(ollama_entries):,}{C.RESET}")

    # --- Top destinations ---
    print_section(f"Top {top_n} Destinations")
    dst_counter = Counter(e["dst"] for e in entries)
    rows = []
    for ip, count in dst_counter.most_common(top_n):
        pct = count / total * 100
        bar_len = int(pct / 2)
        bar = f"{C.BLUE}{'█' * bar_len}{C.DIM}{'░' * (25 - bar_len)}{C.RESET}"
        has_ollama = any(e["dst"] == ip and e["is_ollama"] for e in entries)
        flag = f"  {C.BG_RED}{C.WHITE} OLLAMA {C.RESET}" if has_ollama else ""
        rows.append([fmt_dst(ip, resolve), str(count), f"{pct:5.1f}%", bar + flag])
    print_table(["Destination", "Count", "Pct", ""], rows)

    # --- Top ports ---
    print_section(f"Top {top_n} Destination Ports")
    port_counter = Counter(e["dpt"] for e in entries if e["dpt"] > 0)
    rows = []
    for port, count in port_counter.most_common(top_n):
        pct = count / total * 100
        unusual = port not in NORMAL_OUTBOUND_PORTS
        port_str = port_label(port)
        if unusual:
            port_str = f"{C.YELLOW}{port_str}{C.RESET}"
        rows.append([port_str, str(count), f"{pct:5.1f}%"])
    print_table(["Port", "Count", "Pct"], rows)

    # --- Top source IPs (useful if multiple hoppers log to same file) ---
    src_counter = Counter(e["src"] for e in entries)
    if len(src_counter) > 1:
        print_section(f"Top {top_n} Source Hosts")
        rows = []
        for ip, count in src_counter.most_common(top_n):
            rows.append([fmt_dst(ip, resolve), str(count)])
        print_table(["Source", "Count"], rows)

    # --- Hourly distribution ---
    print_section("Hourly Distribution (last 24h)")
    now = datetime.now()
    cutoff_24h = now - timedelta(hours=24)
    recent = [e for e in entries if e["timestamp"] >= cutoff_24h]
    if recent:
        hourly = Counter(e["timestamp"].hour for e in recent)
        max_count = max(hourly.values()) if hourly else 1
        for hour in range(24):
            count = hourly.get(hour, 0)
            bar_len = int(count / max_count * 40) if max_count > 0 else 0
            bar = f"{C.BLUE}{'█' * bar_len}{C.RESET}"
            print(f"  {hour:02d}:00  {bar} {count}")
    else:
        print(f"  {C.DIM}No entries in the last 24 hours.{C.RESET}")

    # --- Protocol breakdown ---
    print_section("Protocol Breakdown")
    proto_counter = Counter(e["proto"] for e in entries if e["proto"])
    rows = [[proto, str(count)] for proto, count in proto_counter.most_common()]
    print_table(["Protocol", "Count"], rows)


def print_ollama_report(entries, resolve):
    """Dedicated section for Ollama activity — the main reason we're here."""
    ollama = [e for e in entries if e["is_ollama"]]

    print_header("OLLAMA OUTBOUND ACTIVITY")

    if not ollama:
        print(f"\n  {C.GREEN}{C.BOLD}✓ No outbound connections from Ollama detected.{C.RESET}")
        print(f"  {C.DIM}This is the expected result if Ollama is behaving.{C.RESET}")
        return

    # This is the interesting case — Ollama is phoning home
    print(f"\n  {C.BG_RED}{C.WHITE}{C.BOLD} ⚠  OLLAMA MADE {len(ollama):,} OUTBOUND CONNECTION(S) {C.RESET}")
    print()

    dst_counter = Counter((e["dst"], e["dpt"]) for e in ollama)
    rows = []
    for (ip, port), count in dst_counter.most_common():
        first_seen = min(e["timestamp"] for e in ollama if e["dst"] == ip and e["dpt"] == port)
        last_seen = max(e["timestamp"] for e in ollama if e["dst"] == ip and e["dpt"] == port)
        rows.append([
            fmt_dst(ip, resolve),
            port_label(port),
            str(count),
            first_seen.strftime("%m-%d %H:%M"),
            last_seen.strftime("%m-%d %H:%M"),
        ])
    print_table(["Destination", "Port", "Count", "First Seen", "Last Seen"], rows)

    print(f"\n  {C.YELLOW}Action items:{C.RESET}")
    print(f"  • Investigate what Ollama is reaching out to")
    print(f"  • Check if OLLAMA_HOST or model pull configs are set")
    print(f"  • Consider blocking with: firewall-cmd --direct --add-rule ipv4 filter OUTPUT 0 \\")
    print(f"      -m owner --uid-owner ollama -j REJECT")


def print_anomaly_report(entries, baseline, resolve):
    """Flag unusual or first-seen activity."""
    print_header("ANOMALY DETECTION")

    anomalies = []

    # --- Unusual ports (not in the normal set) ---
    unusual_port_entries = [e for e in entries if e["dpt"] > 0 and e["dpt"] not in NORMAL_OUTBOUND_PORTS]
    if unusual_port_entries:
        unusual_ports = Counter((e["dst"], e["dpt"]) for e in unusual_port_entries)
        for (ip, port), count in unusual_ports.most_common(20):
            anomalies.append({
                "type": "UNUSUAL_PORT",
                "severity": "MEDIUM",
                "dst": ip,
                "port": port,
                "count": count,
                "detail": f"Port {port_label(port)} is not in the standard outbound set",
            })

    # --- Blocked attempts (something tried to get out and was denied) ---
    blocked = [e for e in entries if e["is_blocked"]]
    if blocked:
        blocked_dsts = Counter((e["dst"], e["dpt"]) for e in blocked)
        for (ip, port), count in blocked_dsts.most_common(20):
            anomalies.append({
                "type": "BLOCKED_ATTEMPT",
                "severity": "HIGH",
                "dst": ip,
                "port": port,
                "count": count,
                "detail": f"Outbound connection was blocked {count} time(s)",
            })

    # --- Ollama outbound (always flagged) ---
    ollama = [e for e in entries if e["is_ollama"]]
    if ollama:
        ollama_dsts = Counter(e["dst"] for e in ollama)
        for ip, count in ollama_dsts.most_common():
            anomalies.append({
                "type": "OLLAMA_OUTBOUND",
                "severity": "CRITICAL",
                "dst": ip,
                "port": 0,
                "count": count,
                "detail": f"Ollama process initiated {count} outbound connection(s)",
            })

    # --- First-seen destinations (vs. baseline) ---
    if baseline:
        known_dsts = set(baseline.get("known_destinations", []))
        known_dst_ports = set(
            tuple(x) for x in baseline.get("known_destination_ports", [])
        )
        current_dsts = set(e["dst"] for e in entries)
        current_dst_ports = set((e["dst"], e["dpt"]) for e in entries if e["dpt"] > 0)

        new_dsts = current_dsts - known_dsts
        new_dst_ports = current_dst_ports - known_dst_ports

        for ip in new_dsts:
            count = sum(1 for e in entries if e["dst"] == ip)
            anomalies.append({
                "type": "NEW_DESTINATION",
                "severity": "HIGH",
                "dst": ip,
                "port": 0,
                "count": count,
                "detail": "Destination NOT in baseline — never seen before",
            })

        for ip, port in new_dst_ports:
            if ip not in new_dsts:  # avoid double-flagging
                count = sum(1 for e in entries if e["dst"] == ip and e["dpt"] == port)
                anomalies.append({
                    "type": "NEW_DST_PORT",
                    "severity": "MEDIUM",
                    "dst": ip,
                    "port": port,
                    "count": count,
                    "detail": f"Known destination, but port {port_label(port)} is new",
                })

    # --- Print anomalies ---
    if not anomalies:
        if baseline:
            print(f"\n  {C.GREEN}{C.BOLD}✓ No anomalies detected vs. baseline.{C.RESET}")
        else:
            print(f"\n  {C.GREEN}{C.BOLD}✓ No obvious anomalies detected.{C.RESET}")
            print(f"  {C.DIM}Tip: Create a baseline with --save-baseline for better detection.{C.RESET}")
        return

    severity_colors = {
        "CRITICAL": C.BG_RED + C.WHITE,
        "HIGH": C.RED,
        "MEDIUM": C.YELLOW,
        "LOW": C.DIM,
    }
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    anomalies.sort(key=lambda a: (severity_order.get(a["severity"], 99), -a["count"]))

    print(f"\n  Found {C.BOLD}{len(anomalies)}{C.RESET} anomalies:\n")

    rows = []
    for a in anomalies:
        sev = a["severity"]
        sev_str = f"{severity_colors.get(sev, '')}{sev:<8}{C.RESET}"
        dst_str = fmt_dst(a["dst"], resolve)
        port_str = port_label(a["port"]) if a["port"] > 0 else "—"
        rows.append([sev_str, a["type"], dst_str, port_str, str(a["count"]), a["detail"]])
    print_table(["Severity", "Type", "Destination", "Port", "Count", "Detail"], rows)


# =============================================================================
# Baseline management
# =============================================================================

def save_baseline(entries, path):
    """Save current traffic patterns as a known-good baseline."""
    destinations = list(set(e["dst"] for e in entries))
    dst_ports = list(set((e["dst"], e["dpt"]) for e in entries if e["dpt"] > 0))

    baseline = {
        "created": datetime.now().isoformat(),
        "entry_count": len(entries),
        "known_destinations": destinations,
        "known_destination_ports": dst_ports,
        "known_ports": list(set(e["dpt"] for e in entries if e["dpt"] > 0)),
    }

    with open(path, "w") as f:
        json.dump(baseline, f, indent=2)

    print(f"\n{C.GREEN}✓ Baseline saved to {path}{C.RESET}")
    print(f"  {len(destinations)} unique destinations, {len(dst_ports)} unique dst:port pairs")
    print(f"  Use with: outbound_audit.py --baseline {path}")


def load_baseline(path: str):
    """Load a previously saved baseline."""
    if not path:
        return None
    try:
        with open(path, "r") as f:
            baseline = json.load(f)
        print(f"  {C.DIM}Loaded baseline from {path} "
              f"({baseline.get('entry_count', '?')} entries, "
              f"created {baseline.get('created', '?')}){C.RESET}")
        return baseline
    except FileNotFoundError:
        print(f"{C.RED}ERROR:{C.RESET} Baseline file not found: {path}")
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"{C.RED}ERROR:{C.RESET} Invalid JSON in baseline: {path}")
        sys.exit(1)


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Analyze outbound connection logs from firewalld for suspicious activity.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  sudo python outbound_audit.py                          # Analyze default log
  sudo python outbound_audit.py --ollama-only             # Just Ollama activity
  sudo python outbound_audit.py --save-baseline base.json # Snapshot current traffic
  sudo python outbound_audit.py --baseline base.json      # Compare against baseline
  sudo python outbound_audit.py --after "2025-03-20 08:00" --before "2025-03-20 17:00"
        """,
    )
    parser.add_argument("-f", "--file", default="/var/log/outbound-connections.log",
                        help="Log file to analyze (default: /var/log/outbound-connections.log)")
    parser.add_argument("-n", "--top", type=int, default=10,
                        help="Number of top items to show (default: 10)")
    parser.add_argument("--ollama-only", action="store_true",
                        help="Only show Ollama outbound activity")
    parser.add_argument("--no-resolve", action="store_true",
                        help="Skip reverse DNS lookups (faster)")
    parser.add_argument("--baseline", metavar="FILE",
                        help="Compare against a known-good baseline JSON file")
    parser.add_argument("--save-baseline", metavar="FILE",
                        help="Save current traffic patterns as a baseline and exit")
    parser.add_argument("--after", metavar="DATETIME",
                        help="Only include entries after this time (YYYY-MM-DD HH:MM)")
    parser.add_argument("--before", metavar="DATETIME",
                        help="Only include entries before this time (YYYY-MM-DD HH:MM)")

    args = parser.parse_args()
    resolve = not args.no_resolve

    # Read and parse
    print(f"{C.DIM}Reading {args.file}...{C.RESET}")
    entries = read_log_file(args.file)
    print(f"{C.DIM}Parsed {len(entries):,} log entries.{C.RESET}")

    # Time filters
    if args.after:
        try:
            after_dt = datetime.strptime(args.after, "%Y-%m-%d %H:%M")
            entries = [e for e in entries if e["timestamp"] >= after_dt]
        except ValueError:
            print(f"{C.RED}ERROR:{C.RESET} Invalid --after format. Use 'YYYY-MM-DD HH:MM'")
            sys.exit(1)

    if args.before:
        try:
            before_dt = datetime.strptime(args.before, "%Y-%m-%d %H:%M")
            entries = [e for e in entries if e["timestamp"] <= before_dt]
        except ValueError:
            print(f"{C.RED}ERROR:{C.RESET} Invalid --before format. Use 'YYYY-MM-DD HH:MM'")
            sys.exit(1)

    if not entries:
        print(f"\n{C.YELLOW}No entries found in the specified range.{C.RESET}")
        sys.exit(0)

    print(f"{C.DIM}Analyzing {len(entries):,} entries after filters...{C.RESET}")

    # Save baseline and exit
    if args.save_baseline:
        save_baseline(entries, args.save_baseline)
        sys.exit(0)

    # Load baseline for comparison
    baseline = load_baseline(args.baseline) if args.baseline else None

    # Resolve DNS (batch, with progress)
    if resolve:
        unique_ips = set(e["dst"] for e in entries) | set(e["src"] for e in entries)
        print(f"{C.DIM}Resolving {len(unique_ips)} unique IPs (cached)...{C.RESET}")
        for ip in unique_ips:
            resolve_ip(ip)  # warm the cache

    # Reports
    if args.ollama_only:
        print_ollama_report(entries, resolve)
    else:
        print_summary_report(entries, args.top, resolve)
        print_ollama_report(entries, resolve)
        print_anomaly_report(entries, baseline, resolve)

    # Footer
    print(f"\n{C.DIM}{'─' * 78}{C.RESET}")
    print(f"{C.DIM}Log file: {args.file}{C.RESET}")
    if baseline:
        print(f"{C.DIM}Baseline: {args.baseline}{C.RESET}")
    print()


if __name__ == "__main__":
    main()
