#!/usr/bin/env bash
# =============================================================================
# outbound_audit_cron.sh
#
# Daily cron wrapper for outbound_audit.py
# - Runs the audit against the baseline
# - If anomalies found: emails alert + writes report file
# - If clean: writes a one-liner to the report file, no email
#
# Install:
#   sudo cp outbound_audit.py /usr/local/bin/outbound_audit.py
#   sudo cp outbound_audit_cron.sh /usr/local/bin/outbound_audit_cron.sh
#   sudo chmod +x /usr/local/bin/outbound_audit_cron.sh
#   # Add to root crontab:  0 0 * * * EMAIL=you@example.com /usr/local/bin/outbound_audit_cron.sh
#
# Prerequisites:
#   - outbound_audit.py installed at AUDIT_SCRIPT
#   - Baseline already created:
#       sudo python3 /usr/local/bin/outbound_audit.py --save-baseline /etc/outbound-baseline.json
#   - mailx or sendmail available for email alerts
#   - EMAIL environment variable set to the alert recipient
#
# Exit codes from outbound_audit.py:
#   0 = clean
#   1 = anomalies detected
#   2 = Ollama outbound activity detected
# =============================================================================

set -uo pipefail

# --- Configuration -----------------------------------------------------------
AUDIT_SCRIPT="/usr/local/bin/outbound_audit.py"
BASELINE="/etc/outbound-baseline.json"
LOG_FILE="/var/log/outbound-connections.log"
REPORT_DIR="/var/log/outbound-audit-reports"
ALERT_EMAIL="${EMAIL:?ERROR: EMAIL environment variable is not set}"
HOSTNAME=$(hostname --short)

# Python binary — adjust if needed (e.g., /usr/bin/python3.11)
PYTHON="/usr/bin/python3"

# --- Setup -------------------------------------------------------------------
mkdir --parents "${REPORT_DIR}"
TODAY=$(date +%Y-%m-%d)
REPORT_FILE="${REPORT_DIR}/audit-${TODAY}.txt"
YESTERDAY_START=$(date --date="yesterday 00:00" +"%Y-%m-%d %H:%M")
YESTERDAY_END=$(date --date="yesterday 23:59" +"%Y-%m-%d %H:%M")

# --- Run the audit -----------------------------------------------------------
# --no-resolve avoids slow DNS lookups at midnight
# Capture exit code separately so set -u does not abort on non-zero exit.
AUDIT_OUTPUT=$(
    "${PYTHON}" "${AUDIT_SCRIPT}" \
        --file "${LOG_FILE}" \
        --baseline "${BASELINE}" \
        --after "${YESTERDAY_START}" \
        --before "${YESTERDAY_END}" \
        --no-resolve \
        2>/dev/null
) || AUDIT_EXIT=$?

# outbound_audit.py exit code contract:
#   0 = clean, 1 = anomalies, 2 = Ollama outbound
AUDIT_EXIT="${AUDIT_EXIT:-0}"
HAS_ANOMALIES=false
OLLAMA_ALERT=false

if [[ "${AUDIT_EXIT}" -ge 1 ]]; then
    HAS_ANOMALIES=true
fi

if [[ "${AUDIT_EXIT}" -ge 2 ]]; then
    OLLAMA_ALERT=true
fi

# --- Write report file (always) ---------------------------------------------
{
    echo "========================================"
    echo " Outbound Audit Report: ${TODAY}"
    echo " Host: ${HOSTNAME}"
    echo " Period: ${YESTERDAY_START} → ${YESTERDAY_END}"
    echo "========================================"
    echo ""
    if [[ "${HAS_ANOMALIES}" == true ]]; then
        echo " STATUS: ⚠ ANOMALIES DETECTED"
        echo " Ollama outbound: ${OLLAMA_ALERT}"
    else
        echo " STATUS: ✓ CLEAN — no anomalies"
    fi
    echo ""
    echo "${AUDIT_OUTPUT}"
} > "${REPORT_FILE}"

# --- Send email alert (only if anomalies found) -----------------------------
if [[ "${HAS_ANOMALIES}" == true ]]; then
    SUBJECT="[ALERT] ${HOSTNAME}: Outbound connection anomalies detected"
    if [[ "${OLLAMA_ALERT}" == true ]]; then
        SUBJECT="[CRITICAL] ${HOSTNAME}: Ollama made outbound connections!"
    fi

    build_email_body() {
        cat <<EMAIL_EOF
Outbound connection anomalies detected on ${HOSTNAME}.

Date:     ${TODAY} (analyzing yesterday's traffic)
Period:   ${YESTERDAY_START} → ${YESTERDAY_END}
Ollama outbound: ${OLLAMA_ALERT}

Full report: ${REPORT_FILE}

--- Audit output ---

${AUDIT_OUTPUT}

---
This alert was generated by outbound_audit_cron.sh on ${HOSTNAME}.
Reports are saved to ${REPORT_DIR}/
To investigate: sudo python3 ${AUDIT_SCRIPT} --file ${LOG_FILE} --after "${YESTERDAY_START}" --before "${YESTERDAY_END}"
EMAIL_EOF
    }

    # Try mailx first, fall back to mail, then sendmail
    if command -v mailx &>/dev/null; then
        build_email_body | mailx -s "${SUBJECT}" "${ALERT_EMAIL}"
    elif command -v mail &>/dev/null; then
        build_email_body | mail -s "${SUBJECT}" "${ALERT_EMAIL}"
    elif command -v sendmail &>/dev/null; then
        {
            echo "Subject: ${SUBJECT}"
            echo "To: ${ALERT_EMAIL}"
            echo "From: outbound-audit@${HOSTNAME}"
            echo ""
            build_email_body
        } | sendmail "${ALERT_EMAIL}"
    else
        # No mail command available — log a warning so the failure is not silent
        echo "[$(date --iso-8601=seconds)] WARNING: Anomalies found but no mail command available. See ${REPORT_FILE}" \
            >> "${REPORT_DIR}/mail-failures.log"
    fi
fi

# --- Clean up old reports (keep 90 days) -------------------------------------
find "${REPORT_DIR}" -name "audit-*.txt" -mtime +90 -delete 2>/dev/null || true

# --- Log the run to syslog ---------------------------------------------------
if [[ "${HAS_ANOMALIES}" == true ]]; then
    logger -t outbound-audit "Anomalies detected. Ollama: ${OLLAMA_ALERT}. Report: ${REPORT_FILE}"
else
    logger -t outbound-audit "Clean run. Report: ${REPORT_FILE}"
fi
